### ISSUE TITLE
exec and fork

### ISSUE THREAD

**Issue by norf315** [sande807/4061projects#4]
This is the part that actually compiles the program. Go through the linked list structure, and if there are dependencies, fork() to create a child and then continue the process on the child which will either run the dependencies or execute the command via execl(). the parent will wait for all children to finish before execl() themselves.

**Comment by sande807** [comment]
instead of the execl() command, we need to be using the execvp() command, which accepts two arguments - (const char\* file, char\* const argv[]). we also should look into using some of the functions in util.c, such as makeargv.

**Comment by norf315** [comment]
got it to fork sort of. it creates children and those children search to see if the dependency they were given match a target that needs to be compiled. Not sure where to go from there. I also added number of targets by having parse return an integer related to the number of targets. The program still checks if it returns -1 but now we can use "num" in the main program to check the number of targets.

**Comment by sande807** [comment]
we've been forking/execing in the wrong place i believe. perhaps we could creating a function that we fork and exec in, to keep things clean and easy.

**Comment by norf315** [comment]
fixed the clean issue in a very brute force way, we could do it in a more complicated way but why bother
