### ISSUE TITLE
target_t object

### ISSUE THREAD

**Issue by sande807** [sande807/4061projects#5]
i ran into trouble when trying to use a target_t object in main. it doesn't recognize any of the work done in parse, and if i declare one in parse then, main doesn't recognize the object. i tried to add a second argument to the parse()) function, a target_t object, but that was unsuccessful and the error list got messy and long very quickly. we need to figure out how to use a target_t object with all of the attributes set correctly via the parse() function in the main() function.

**Comment by norf315** [comment]
replaced target_t object with an array of targets. passed that in to the parse function and filled it up, so it all works well now. It's not dynamically allocated but it will work.
